-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Exception.SkelLatte where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Grammar.AbsLatte

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Grammar.AbsLatte.Ident -> Result
transIdent x = case x of
  Grammar.AbsLatte.Ident string -> failure x

transProgram :: Show a => Grammar.AbsLatte.Program' a -> Result
transProgram x = case x of
  Grammar.AbsLatte.Program _ topdefs -> failure x

transTopDef :: Show a => Grammar.AbsLatte.TopDef' a -> Result
transTopDef x = case x of
  Grammar.AbsLatte.FnDef _ type_ ident args block -> failure x
  Grammar.AbsLatte.GloDecl _ type_ items -> failure x

transArg :: Show a => Grammar.AbsLatte.Arg' a -> Result
transArg x = case x of
  Grammar.AbsLatte.Arg _ type_ ident -> failure x

transBlock :: Show a => Grammar.AbsLatte.Block' a -> Result
transBlock x = case x of
  Grammar.AbsLatte.Block _ stmts -> failure x

transStmt :: Show a => Grammar.AbsLatte.Stmt' a -> Result
transStmt x = case x of
  Grammar.AbsLatte.Empty _ -> failure x
  Grammar.AbsLatte.BStmt _ block -> failure x
  Grammar.AbsLatte.Decl _ type_ items -> failure x
  Grammar.AbsLatte.Ass _ ident expr -> failure x
  Grammar.AbsLatte.Incr _ ident -> failure x
  Grammar.AbsLatte.Decr _ ident -> failure x
  Grammar.AbsLatte.Ret _ expr -> failure x
  Grammar.AbsLatte.VRet _ -> failure x
  Grammar.AbsLatte.Cond _ expr stmt -> failure x
  Grammar.AbsLatte.CondElse _ expr stmt1 stmt2 -> failure x
  Grammar.AbsLatte.While _ expr stmt -> failure x
  Grammar.AbsLatte.Break _ -> failure x
  Grammar.AbsLatte.Continue _ -> failure x
  Grammar.AbsLatte.STopDef _ topdef -> failure x
  Grammar.AbsLatte.SExp _ expr -> failure x

transItem :: Show a => Grammar.AbsLatte.Item' a -> Result
transItem x = case x of
  Grammar.AbsLatte.NoInit _ ident -> failure x
  Grammar.AbsLatte.Init _ ident expr -> failure x

transType :: Show a => Grammar.AbsLatte.Type' a -> Result
transType x = case x of
  Grammar.AbsLatte.Int _ -> failure x
  Grammar.AbsLatte.Str _ -> failure x
  Grammar.AbsLatte.Bool _ -> failure x
  Grammar.AbsLatte.Void _ -> failure x
  Grammar.AbsLatte.Fun _ type_ types -> failure x

transExpr :: Show a => Grammar.AbsLatte.Expr' a -> Result
transExpr x = case x of
  Grammar.AbsLatte.EVar _ ident -> failure x
  Grammar.AbsLatte.ELitInt _ integer -> failure x
  Grammar.AbsLatte.ELitTrue _ -> failure x
  Grammar.AbsLatte.ELitFalse _ -> failure x
  Grammar.AbsLatte.EApp _ ident exprs -> failure x
  Grammar.AbsLatte.EString _ string -> failure x
  Grammar.AbsLatte.Neg _ expr -> failure x
  Grammar.AbsLatte.Not _ expr -> failure x
  Grammar.AbsLatte.EMul _ expr1 mulop expr2 -> failure x
  Grammar.AbsLatte.EAdd _ expr1 addop expr2 -> failure x
  Grammar.AbsLatte.ERel _ expr1 relop expr2 -> failure x
  Grammar.AbsLatte.EAnd _ expr1 expr2 -> failure x
  Grammar.AbsLatte.EOr _ expr1 expr2 -> failure x
  Grammar.AbsLatte.ELambda _ type_ args block -> failure x

transAddOp :: Show a => Grammar.AbsLatte.AddOp' a -> Result
transAddOp x = case x of
  Grammar.AbsLatte.Plus _ -> failure x
  Grammar.AbsLatte.Minus _ -> failure x

transMulOp :: Show a => Grammar.AbsLatte.MulOp' a -> Result
transMulOp x = case x of
  Grammar.AbsLatte.Times _ -> failure x
  Grammar.AbsLatte.Div _ -> failure x
  Grammar.AbsLatte.Mod _ -> failure x

transRelOp :: Show a => Grammar.AbsLatte.RelOp' a -> Result
transRelOp x = case x of
  Grammar.AbsLatte.LTH _ -> failure x
  Grammar.AbsLatte.LE _ -> failure x
  Grammar.AbsLatte.GTH _ -> failure x
  Grammar.AbsLatte.GE _ -> failure x
  Grammar.AbsLatte.EQU _ -> failure x
  Grammar.AbsLatte.NE _ -> failure x
